image: rambabusaravanan/firebase

stages:
  - deploy

cache:
  paths:
    - node_modules/
  key: "$CI_BUILD_REPO"

deploy-prod:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - yarn
    - yarn run build
    - firebase use kairos-282000 --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:production -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN

deploy-staging:
    stage: deploy
    environment: Staging
    only:
      - staging
      - merge_requests
    script:
      - yarn
      - yarn run build
      - firebase use kairos-282000 --token $FIREBASE_TOKEN
      - firebase deploy --only hosting:staging -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN