
stages:
  - build
  - test
  - post test
  - staging
  - production

cache:
  paths:
    - node_modules/
  key: "$CI_BUILD_REPO"

deploy-prod:
  image: rambabusaravanan/firebase
  stage: production
  environment: Production
  only:
    - master
  script:
    - yarn
    - yarn run build
    - firebase use kairos-282000 --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:production -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN

deploy-staging:
  image: rambabusaravanan/firebase
  stage: staging
  environment: Staging
  only:
    - staging
  script:
    - yarn
    - yarn run build
    - firebase use kairos-282000 --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:staging -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN


variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

sonarcloud-check:
  stage: post test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
