
stages:
  - build
  - test
  - post test
  - staging
  - production

cache:
  paths:
    - node_modules/
    - ~/.npm
  key: "$CI_BUILD_REPO"

web-testing:
  image: trion/ng-cli-karma
  stage: test
  cache:
    policy: pull
  script:
    - rm ./package-lock.json
    - npm install
    - npm run test
  only:
    - merge_requests
    - master
    - staging
  artifacts:
    paths:
        - coverage/

deploy-prod:
  image: rambabusaravanan/firebase
  stage: production
  environment: Production
  only:
    - master
  script:
    - yarn
    - yarn run build --prod
    - firebase use kairos-282000 --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:production -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN

deploy-staging:
  image: rambabusaravanan/firebase
  stage: staging
  environment: Staging
  only:
    - staging
  script:
    - yarn
    - yarn run build
    - firebase use kairos-282000 --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:staging -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN


variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

sonarcloud-check:
  stage: post test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master
    - staging
  needs:
    - web-testing
